/* Chat intents — part 2: es, it, pt */
window.CHAT_INTENTS = window.CHAT_INTENTS || {};

Object.assign(window.CHAT_INTENTS, {
  es: {
    name: ["quién es eslam", "quien es eslam", "eslam dawoud", "tu nombre", "quién eres", "sobre eslam", "preséntate"],
    role: ["qué hace eslam", "que hace eslam", "rol", "cargo", "especialidad", "profesión"],
    skills: ["habilidades", "tecnologías", "lenguajes", "herramientas", "stack", "sabe"],
    projects: ["proyectos", "proyecto", "portafolio", "aplicaciones", "creado"],
    exp: ["experiencia", "carrera", "trayectoria", "trabajo", "pasante", "empleos"],
    edu: ["educación", "estudios", "universidad", "título", "estudiante"],
    services: ["servicios", "contratar", "trabajar con", "ofrecer", "ayuda"],
    contact: ["contacto", "email", "teléfono", "correo", "número", "contactar"],
    location: ["ubicación", "dónde", "giza", "egipto", "vive"],
    stack: ["flujo", "arquitectura", "capas", "frontend", "backend", "full stack"],
    depi: ["depi", "iniciativa", "egipto digital", "formación", "pasante"],
    cv: ["cv", "currículum", "resumen", "descargar"],
    github: ["github", "código", "repositorios", "código fuente"],
    linkedin: ["linkedin", "perfil", "red", "conectar"],
    why: ["por qué", "contratar", "fortalezas", "cualidades"],
    fee: ["precio", "costo", "tarifa", "pago", "presupuesto"],
  },

  it: {
    name: ["chi è eslam", "eslam dawoud", "il tuo nome", "chi sei", "su eslam", "presentati"],
    role: ["cosa fa eslam", "ruolo", "professione", "specializzazione", "lavoro"],
    skills: ["competenze", "tecnologie", "linguaggi", "strumenti", "stack", "sa"],
    projects: ["progetti", "progetto", "portfolio", "applicazioni", "creato"],
    exp: ["esperienza", "carriera", "percorso", "lavoro", "tirocinante", "impieghi"],
    edu: ["istruzione", "studi", "università", "laurea", "studente"],
    services: ["servizi", "assumere", "collaborare", "offrire", "aiuto"],
    contact: ["contatto", "email", "telefono", "numero", "raggiungere", "scrivere"],
    location: ["posizione", "dove", "giza", "egitto", "vive"],
    stack: ["flusso", "architettura", "livelli", "frontend", "backend", "full stack"],
    depi: ["depi", "iniziativa", "egitto digitale", "formazione", "tirocinio"],
    cv: ["cv", "curriculum", "resume", "scaricare"],
    github: ["github", "codice", "repository", "repository"],
    linkedin: ["linkedin", "profilo", "rete", "collegarsi"],
    why: ["perché", "assumere", "punti di forza", "qualità"],
    fee: ["prezzo", "costo", "tariffa", "pagamento", "budget"],
  },

  pt: {
    name: ["quem é eslam", "eslam dawoud", "seu nome", "quem é você", "sobre eslam", "apresente"],
    role: ["o que eslam faz", "papel", "cargo", "especialidade", "profissão"],
    skills: ["habilidades", "tecnologias", "linguagens", "ferramentas", "stack", "sabe"],
    projects: ["projetos", "projeto", "portfólio", "aplicações", "criou"],
    exp: ["experiência", "carreira", "trajetória", "trabalho", "estagiário", "empregos"],
    edu: ["educação", "estudos", "universidade", "diploma", "estudante"],
    services: ["serviços", "contratar", "trabalhar com", "oferecer", "ajuda"],
    contact: ["contato", "email", "telefone", "número", "mensagem", "falar"],
    location: ["localização", "onde", "gizé", "egito", "mora"],
    stack: ["fluxo", "arquitetura", "camadas", "frontend", "backend", "full stack"],
    depi: ["depi", "iniciativa", "egito digital", "treinamento", "estágio"],
    cv: ["currículo", "cv", "resumo", "baixar"],
    github: ["github", "código", "repositórios", "código-fonte"],
    linkedin: ["linkedin", "perfil", "rede", "conectar"],
    why: ["por que", "contratar", "pontos fortes", "qualidades"],
    fee: ["preço", "custo", "tarifa", "pagamento", "orçamento"],
  },
});