/* Chat intents — part 1: en, ar, fr, de */
window.CHAT_INTENTS = window.CHAT_INTENTS || {};

Object.assign(window.CHAT_INTENTS, {
  en: {
    name: ["who is eslam", "eslam dawoud", "your name", "who are you", "about eslam", "introduce", "tell me about eslam"],
    role: ["what does eslam", "what is eslam", "role", "job title", "what do you do", "specializes"],
    skills: ["skills", "technologies", "tech stack", "languages", "tools", "what can eslam", "knows"],
    projects: ["projects", "project", "portfolio", "built", "repos", "applications"],
    exp: ["experience", "career", "work history", "worked", "trainee", "where did eslam", "jobs"],
    edu: ["education", "study", "university", "degree", "college", "student", "academic"],
    services: ["services", "hire", "work with", "freelance", "offer", "help with"],
    contact: ["contact", "email", "phone", "reach", "number", "gmail", "message him"],
    location: ["location", "located", "where is eslam", "giza", "egypt", "country", "live"],
    stack: ["stack", "flow", "how does", "architecture", "layers", "frontend", "backend", "full stack"],
    depi: ["depi", "initiative", "digital egypt", "training", "trainee", "pioneers"],
    cv: ["cv", "resume", "curriculum", "download"],
    github: ["github", "code", "repositories", "repo"],
    linkedin: ["linkedin", "profile", "network", "connect"],
    why: ["why", "hire", "reasons", "strengths", "good at"],
    fee: ["price", "cost", "rate", "charge", "pay", "budget"],
  },

  ar: {
    name: ["من هو اسلام", "اسلام داود", "اسمك", "من انت", "عرف عن نفسك", "عني"],
    role: ["دور", "عمله", "وظيفته", "ماذا يفعل", "مجال", "تخصص"],
    skills: ["مهارات", "تقنيات", "لغات", "تكنولوجيا", "ماذا يعرف", "المكدس", "يعرف"],
    projects: ["مشاريع", "مشروع", "أعمال", "بنى", "تطبيقات"],
    exp: ["خبرة", "خبراته", "عمل سابق", "مسار", "متدرب", "تدريب"],
    edu: ["تعليم", "دراسة", "جامعة", "شهادة", "طالب", "دراسته"],
    services: ["خدمات", "توظيف", "العمل معه", "مشروعك", "مساعدته"],
    contact: ["تواصل", "بريد", "هاتف", "رقم", "الايميل", "مراسلة"],
    location: ["مكان", "عنوان", "الجيزة", "مصر", "الدولة", "يعيش"],
    stack: ["مسار", "كيف", "طبقات", "واجهة", "خلفية", "فول ستاك"],
    depi: ["رواد", "مصر الرقمية", "مبادرة", "التدريب"],
    cv: ["سيرة ذاتية", "سيڤي", "عف", "تحميل السيرة"],
    github: ["جيت هاب", "كود", "مستودعات", "أكواد"],
    linkedin: ["لينكد ان", "بروفايل", "شبكة", "تواصل"],
    why: ["لماذا", "مميزات", "نقاط قوة", "السبب"],
    fee: ["السعر", "التكلفة", "رسوم", "مقابل", "الدفع"],
  },

  fr: {
    name: ["qui est eslam", "eslam dawoud", "ton nom", "qui es tu", "à propos d'eslam", "présente"],
    role: ["que fait eslam", "rôle", "poste", "spécialité", "métier"],
    skills: ["compétences", "technologies", "langages", "outils", "stack", "sait faire"],
    projects: ["projets", "projet", "portfolio", "créations", "applications"],
    exp: ["expérience", "carrière", "parcours", "travail", "stagiaire", "emplois"],
    edu: ["études", "éducation", "université", "diplôme", "étudiant"],
    services: ["services", "embaucher", "travailler avec", "proposition"],
    contact: ["contact", "email", "téléphone", "joindre", "numero"],
    location: ["localisation", "où", "gizeh", "egypte", "vit"],
    stack: ["pile", "flux", "architecture", "frontend", "backend"],
    depi: ["depi", "initiative", "egypte numérique", "formation", "stage"],
    cv: ["cv", "curriculum", "résumé", "télécharger"],
    github: ["github", "code", "dépôts", "dépôt"],
    linkedin: ["linkedin", "profil", "réseau", "connecter"],
    why: ["pourquoi", "engager", "forces", "atouts"],
    fee: ["prix", "tarif", "coût", "paiement", "forfait"],
  },

  de: {
    name: ["wer ist eslam", "eslam dawoud", "dein name", "wer bist du", "über eslam", "vorstellen"],
    role: ["was macht eslam", "rolle", "beruf", "tätigkeit", "spezialgebiet"],
    skills: ["fähigkeiten", "kenntnisse", "technologien", "sprachen", "werkzeuge", "stack"],
    projects: ["projekte", "projekt", "portfolio", "gebaut", "anwendungen"],
    exp: ["erfahrung", "karriere", "werdegang", "arbeit", "praktikum", "praktikant"],
    edu: ["bildung", "studium", "universität", "abschluss", "student"],
    services: ["dienstleistungen", "anheuern", "zusammenarbeit", "angebot"],
    contact: ["kontakt", "email", "telefon", "erreichen", "nummer"],
    location: ["wohnt", "wo", "gizeh", "ägypten", "standort"],
    stack: ["ablauf", "architektur", "schichten", "frontend", "backend", "fullstack"],
    depi: ["depi", "initiative", "digitales ägypten", "schulung", "fortbildung"],
    cv: ["lebenslauf", "cv", "resume", "download", "herunterladen"],
    github: ["github", "code", "repository", "repositories"],
    linkedin: ["linkedin", "profil", "netzwerk", "verbinden"],
    why: ["warum", "einstellen", "stärken", "stärke"],
    fee: ["preis", "kosten", "tarif", "honorar", "zahlung"],
  },
});